-- 리플핏 스키마 베이스라인 (#57)
--
-- 이 파일은 도입 시점의 JPA 엔티티에서 생성된 스키마를 그대로 옮긴 것이다.
-- 빈 DB에 이 마이그레이션을 적용한 뒤 Hibernate ddl-auto=validate가 통과해야 하며,
-- 그 사실은 FlywayBaselineTest가 실제 PostgreSQL 컨테이너로 검증한다.
--
-- 이미 ddl-auto=update로 스키마가 만들어진 기존 DB는
-- spring.flyway.baseline-on-migrate=true 에 의해 V1을 건너뛴다.
-- (기존 DB와 이 파일의 차이는 컬럼 순서·제약 이름뿐이며 validate는 둘을 구분하지 않는다)
--
-- 앞으로 스키마 변경은 반드시 V2, V3... 로 추가한다. 이 파일은 수정하지 않는다.

-- ── 사용자 ──────────────────────────────────────────────────────────────
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(200)  NOT NULL,
    password    VARCHAR(255)  NOT NULL,
    name        VARCHAR(100)  NOT NULL,
    store_name  VARCHAR(200)  NOT NULL,
    created_at  TIMESTAMP(6)  NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- ── 구독 (사용자당 1건) ─────────────────────────────────────────────────
CREATE TABLE subscriptions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT        NOT NULL,
    plan             VARCHAR(20)   NOT NULL,
    status           VARCHAR(20)   NOT NULL,
    monthly_price    INTEGER       NOT NULL,
    billing_key      VARCHAR(200),
    started_at       TIMESTAMP(6)  NOT NULL,
    next_billing_at  TIMESTAMP(6),
    updated_at       TIMESTAMP(6)  NOT NULL,
    CONSTRAINT uk_subscriptions_user UNIQUE (user_id),
    CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_subscriptions_plan   CHECK (plan   IN ('STARTER', 'GROWTH', 'PRO')),
    CONSTRAINT ck_subscriptions_status CHECK (status IN ('TRIAL', 'ACTIVE', 'CANCELED'))
);

-- ── 응대 정책 ───────────────────────────────────────────────────────────
CREATE TABLE policies (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT        NOT NULL,
    type        VARCHAR(30)   NOT NULL,
    title       VARCHAR(200)  NOT NULL,
    content     TEXT          NOT NULL,
    created_at  TIMESTAMP(6)  NOT NULL,
    updated_at  TIMESTAMP(6)  NOT NULL,
    CONSTRAINT fk_policies_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_policies_type CHECK (
        type IN ('SHIPPING', 'EXCHANGE_RETURN', 'SIZE_GUIDE', 'RESTOCK', 'GENERAL'))
);

-- ── 고객 문의 ───────────────────────────────────────────────────────────
-- content는 PII 마스킹을 거친 본문만 저장한다. 원문은 저장하지 않는다.
CREATE TABLE inquiries (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT        NOT NULL,
    channel              VARCHAR(50),
    customer_name        VARCHAR(50),
    order_no             VARCHAR(50),
    product_name         VARCHAR(300),
    content              TEXT          NOT NULL,
    status               VARCHAR(30)   NOT NULL,
    category             VARCHAR(30),
    category_confidence  DOUBLE PRECISION,
    pii_masked_count     INTEGER       NOT NULL,
    received_at          TIMESTAMP(6)  NOT NULL,
    created_at           TIMESTAMP(6)  NOT NULL,
    CONSTRAINT fk_inquiries_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_inquiries_status CHECK (
        status IN ('RECEIVED', 'PROCESSING', 'DRAFTED', 'NEEDS_REVIEW', 'APPROVED', 'SENT', 'FAILED')),
    CONSTRAINT ck_inquiries_category CHECK (
        category IN ('SIZE', 'SHIPPING', 'EXCHANGE_RETURN', 'COLOR', 'RESTOCK', 'OTHER'))
);

CREATE INDEX idx_inquiry_user_status   ON inquiries (user_id, status);
CREATE INDEX idx_inquiry_user_received ON inquiries (user_id, received_at);

-- ── 답변 초안 (문의당 1건) ──────────────────────────────────────────────
CREATE TABLE answer_drafts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_id         BIGINT        NOT NULL,
    ai_content         TEXT          NOT NULL,
    content            TEXT          NOT NULL,
    guard_note         TEXT,
    cited_policy_ids   VARCHAR(500),
    generated_by       VARCHAR(100),
    approved_at        TIMESTAMP(6),
    sent_at            TIMESTAMP(6),
    created_at         TIMESTAMP(6)  NOT NULL,
    updated_at         TIMESTAMP(6)  NOT NULL,
    CONSTRAINT uk_answer_drafts_inquiry UNIQUE (inquiry_id),
    CONSTRAINT fk_answer_drafts_inquiry FOREIGN KEY (inquiry_id) REFERENCES inquiries (id)
);

-- ── 리뷰 ────────────────────────────────────────────────────────────────
CREATE TABLE reviews (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL,
    product_name    VARCHAR(300),
    content         TEXT          NOT NULL,
    rating          INTEGER       NOT NULL,
    sentiment       VARCHAR(20)   NOT NULL,
    issue_keywords  VARCHAR(200),
    written_at      TIMESTAMP(6)  NOT NULL,
    created_at      TIMESTAMP(6)  NOT NULL,
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_reviews_sentiment CHECK (sentiment IN ('POSITIVE', 'NEUTRAL', 'NEGATIVE'))
);

CREATE INDEX idx_review_user_written ON reviews (user_id, written_at);

-- ── 주간 리포트 ─────────────────────────────────────────────────────────
CREATE TABLE weekly_reports (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT        NOT NULL,
    week_start  DATE          NOT NULL,
    week_end    DATE          NOT NULL,
    status      VARCHAR(20)   NOT NULL,
    payload     TEXT,
    created_at  TIMESTAMP(6)  NOT NULL,
    CONSTRAINT fk_weekly_reports_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_weekly_reports_status CHECK (status IN ('GENERATING', 'READY', 'FAILED'))
);
